/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import com.sun.media.sound.AuFileReader;
import core.db.entity.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rastislav
 */
public class adminMainFrame extends javax.swing.JFrame {
private User userF;
    /**
     * Creates new form adminMainFrame
     * @param user prihlaseny uzivatel
     */
    public adminMainFrame(User user) {
        initComponents();
        userF = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spravaKlientovButton1 = new javax.swing.JButton();
        spravaBankButton2 = new javax.swing.JButton();
        odhlasitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        spravaKlientovButton1.setText("Sprava Klientov");
        spravaKlientovButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spravaKlientovButton1ActionPerformed(evt);
            }
        });

        spravaBankButton2.setText("Sprava Bank");
        spravaBankButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spravaBankButton2ActionPerformed(evt);
            }
        });

        odhlasitButton1.setText("Odhlasit");
        odhlasitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odhlasitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(spravaKlientovButton1)
                .addGap(52, 52, 52)
                .addComponent(spravaBankButton2)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(odhlasitButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(odhlasitButton1)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spravaKlientovButton1)
                    .addComponent(spravaBankButton2))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spravaKlientovButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spravaKlientovButton1ActionPerformed
        adminUserFrame auFrame = new adminUserFrame(userF);
        auFrame.setVisible(true);
    }//GEN-LAST:event_spravaKlientovButton1ActionPerformed

    private void spravaBankButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spravaBankButton2ActionPerformed
    try {
        adminBankFrame abFrame = new adminBankFrame(userF);
        abFrame.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(adminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_spravaBankButton2ActionPerformed

    private void odhlasitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odhlasitButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_odhlasitButton1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton odhlasitButton1;
    private javax.swing.JButton spravaBankButton2;
    private javax.swing.JButton spravaKlientovButton1;
    // End of variables declaration//GEN-END:variables
}
