/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.Bank;
import core.db.entity.User;
import core.db.impl.BankDaoImpl;
import core.db.ints.BankDao;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rastislav
 */
public class adminBankFrame extends javax.swing.JFrame {

    private static BankDao bankDao = new BankDaoImpl();

    /**
     * Creates new form userAdminFrame
     */
 

    public adminBankFrame(User user) throws SQLException {
        initComponents();
        DefaultTableModel tableModel = (DefaultTableModel)bankTable1.getModel();
        for (int i = 0; i < bankDao.getAll().size(); i++) {
            Long id = bankDao.getAll().get(i).getId();
            String meno = bankDao.getAll().get(i).getName();
            Double rating = bankDao.getAll().get(i).getPrimeInterestRate();
            Object[] data = {id, meno, rating};
            tableModel.addRow(data);
            }
      
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bankTable1 = new javax.swing.JTable();
        pridajButton1 = new javax.swing.JButton();
        vymazButton1 = new javax.swing.JButton();
        menoTextField1 = new javax.swing.JTextField();
        menoLabel1 = new javax.swing.JLabel();
        RatingLabel1 = new javax.swing.JLabel();
        ratingTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bankTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Meno", "Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bankTable1);

        pridajButton1.setText("Pridaj");
        pridajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButton1ActionPerformed(evt);
            }
        });

        vymazButton1.setText("Vymaz");
        vymazButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazButton1ActionPerformed(evt);
            }
        });

        menoLabel1.setText("Meno");

        RatingLabel1.setText("Rating");

        ratingTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingTextField1ActionPerformed(evt);
            }
        });
        ratingTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ratingTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vymazButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridajButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menoLabel1)
                            .addComponent(RatingLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridajButton1)
                    .addComponent(menoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menoLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingLabel1)
                    .addComponent(ratingTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(vymazButton1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButton1ActionPerformed
        List<Boolean> vyplnenost = new ArrayList<>();
        Boolean mozesUlozit = true;
        if (menoTextField1.getText().length() < 50) {
            novaBanka = new Bank();
            novaBanka.setName(menoTextField1.getText());
            vyplnenost.add(true);
        } else {
            menoTextField1.setText("Nespravne vyplnene data");
            vyplnenost.add(false);
        }
        if (ratingTextField1.getText() != null) {
            novaBanka.setPrimeInterestRate(Double.parseDouble(ratingTextField1.getText()));
            vyplnenost.add(true);
        } else {
            ratingTextField1.setText("Nevyplnený rating");
            vyplnenost.add(false);
        }
        for (Boolean boolean1 : vyplnenost) {
            if (!boolean1) {
                mozesUlozit = false;
            }
        }
        if (mozesUlozit) {
            bankDao.saveBank(novaBanka);
        }
    }//GEN-LAST:event_pridajButton1ActionPerformed

    private void vymazButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazButton1ActionPerformed
        bankDao.deleteBank(bankDao.getById((long) bankTable1.getSelectedRow()));
    }//GEN-LAST:event_vymazButton1ActionPerformed

    private void ratingTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingTextField1ActionPerformed

    }//GEN-LAST:event_ratingTextField1ActionPerformed

    private void ratingTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ratingTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }

    }//GEN-LAST:event_ratingTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RatingLabel1;
    private javax.swing.JTable bankTable1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menoLabel1;
    private javax.swing.JTextField menoTextField1;
    private javax.swing.JButton pridajButton1;
    private javax.swing.JTextField ratingTextField1;
    private javax.swing.JButton vymazButton1;
    // End of variables declaration//GEN-END:variables
    private static Bank novaBanka;

}
