/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.User;
import core.db.entity.Bank;
import core.db.impl.BankDaoImpl;
import core.db.impl.UserDaoImpl;
import core.db.ints.BankDao;
import core.db.ints.UserDao;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rastislav, Martin
 */
public class adminUserFrame extends javax.swing.JFrame {

    private static BankDao bankDao = new BankDaoImpl();
    private static UserDao userDao = new UserDaoImpl();    /**
     * Creates new form adminBankFrame
     */
    
     public void inicializujTabulku(){
        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
        List<User> users = userDao.getAll();
        jTable1.removeAll();
        tableModel.setNumRows(users.size());
        for (int i = 0; i < users.size(); i++) {
            Long id = users.get(i).getId();
            Long idB = users.get(i).getIdB();
            String role = users.get(i).getRole();
            String meno = users.get(i).getName();
            Object[] data = {id, idB, role, meno};
            tableModel.setValueAt(id, i, 0);
            tableModel.setValueAt(idB, i, 1);
            tableModel.setValueAt(role, i, 2);
            tableModel.setValueAt(meno, i, 3);
            }
     }

    public adminUserFrame(User user) {
        initComponents();
        inicializujTabulku();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pridajButton1 = new javax.swing.JButton();
        vymazButton2 = new javax.swing.JButton();
        menoTextField = new javax.swing.JTextField();
        menoLabel1 = new javax.swing.JLabel();
        bankaComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rolaLabel2 = new javax.swing.JLabel();
        rolaComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "IdB", "Role", "Meno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pridajButton1.setText("Pridaj");
        pridajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButton1ActionPerformed(evt);
            }
        });

        vymazButton2.setText("Vymaz");
        vymazButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazButton2ActionPerformed(evt);
            }
        });

        menoLabel1.setText("Meno:");

        bankaComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bankaComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Banka:");

        rolaLabel2.setText("Rola:");

        rolaComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rolaComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolaComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vymazButton2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridajButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rolaLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rolaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menoLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(menoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(bankaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridajButton1)
                    .addComponent(menoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menoLabel1)
                    .addComponent(bankaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolaLabel2)
                    .addComponent(rolaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(vymazButton2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vymazButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazButton2ActionPerformed
        userDao.deleteUser(userDao.getById((long)  jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        inicializujTabulku();
    }//GEN-LAST:event_vymazButton2ActionPerformed

    private void pridajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButton1ActionPerformed
         List<Boolean> vyplnenost = new ArrayList<>();
        Boolean mozesUlozit = true;
        if (menoTextField.getText().length() < 50) {
            novyUser = new User();
            novyUser.setName(menoTextField.getText());
            vyplnenost.add(true);
        } else {
            menoTextField.setText("Nespravne vyplnene data");
            vyplnenost.add(false);
        }
        
        if (rolaComboBox1.getSelectedIndex() != -1) {
            novyUser.setRole(rolaComboBox1.getItemAt(rolaComboBox1.getSelectedIndex()));
        } else {
            vyplnenost.add(false);
        }
        
        if (bankaComboBox1.getSelectedIndex() != -1) {
            novyUser.setIdB((long) bankaComboBox1.getSelectedIndex());
        } else {
            vyplnenost.add(false);
        }
        for (Boolean boolean1 : vyplnenost) {
            if (!boolean1) {
                mozesUlozit = false;
            }
        }
        if (mozesUlozit) {
            userDao.saveUser(novyUser);
        }
    }//GEN-LAST:event_pridajButton1ActionPerformed

    private void rolaComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolaComboBox1ActionPerformed
        rolaComboBox1.addItem("administrator");
        rolaComboBox1.addItem("bank");
        rolaComboBox1.addItem("user");
    }//GEN-LAST:event_rolaComboBox1ActionPerformed

    private void bankaComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaComboBox1ActionPerformed
        List<Bank> banky = bankDao.getAll();
        for (int i = 0; i < banky.size(); i++) {
            Long idB = banky.get(i).getId();
            bankaComboBox1.addItem(idB.toString());
        }
    }//GEN-LAST:event_bankaComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bankaComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel menoLabel1;
    private javax.swing.JTextField menoTextField;
    private javax.swing.JButton pridajButton1;
    private javax.swing.JComboBox<String> rolaComboBox1;
    private javax.swing.JLabel rolaLabel2;
    private javax.swing.JButton vymazButton2;
    // End of variables declaration//GEN-END:variables
    private static User novyUser;

}
