/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.User;
import core.db.entity.Bank;
import core.db.entity.Condition;
import core.db.impl.BankDaoImpl;
import core.db.impl.ConditionDaoImpl;
import core.db.ints.BankDao;
import core.db.ints.ConditionDao;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rastislav, Martin
 */
public class bankFrame extends javax.swing.JFrame {
private User userF;

    private static ConditionDao podmienkaDao = new ConditionDaoImpl();
    
    public void inicializujTabulku(){
    DefaultTableModel tableModel = (DefaultTableModel)podmienkyTable.getModel();
        List<Condition> podmienky = podmienkaDao.getAll();
        podmienkyTable.removeAll();
        tableModel.setNumRows(podmienky.size());
        for (int i = 0; i < podmienky.size(); i++) {
            Long id = podmienky.get(i).getId();
            String description = podmienky.get(i).getDescription();
            String expression = podmienky.get(i).getExpression();
            Object[] data = {id, description, expression};
            tableModel.setValueAt(id, i, 0);
            tableModel.setValueAt(description, i, 1);
            tableModel.setValueAt(expression, i, 2);
            }
    }
    /**
     * Creates new form bankFrame
     */
    public bankFrame(User user) {
        userF = user;
        initComponents();
        inicializujTabulku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        podmienkyTable = new javax.swing.JTable();
        pridatPodmienkuButton = new javax.swing.JButton();
        zmazatPodmienkuButton = new javax.swing.JButton();
        neaktivneRadioButton = new javax.swing.JRadioButton();
        vsetky = new javax.swing.JRadioButton();
        aktivneRadioButton = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        podmienkyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Description", "Expression"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(podmienkyTable);

        pridatPodmienkuButton.setText("Pridat podmienku");
        pridatPodmienkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatPodmienkuButtonActionPerformed(evt);
            }
        });

        zmazatPodmienkuButton.setText("Zmazat podmienku");
        zmazatPodmienkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazatPodmienkuButtonActionPerformed(evt);
            }
        });

        neaktivneRadioButton.setText("neaktivne");

        vsetky.setText("vsetky");

        aktivneRadioButton.setText("aktivne");
        aktivneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivneRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridatPodmienkuButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zmazatPodmienkuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsetky)
                            .addComponent(neaktivneRadioButton)
                            .addComponent(aktivneRadioButton))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pridatPodmienkuButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(aktivneRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(zmazatPodmienkuButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neaktivneRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vsetky)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatPodmienkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatPodmienkuButtonActionPerformed
       podmienkaFrame pFrame = null;
            pFrame = new podmienkaFrame(userF);
            pFrame.setVisible(true);
        inicializujTabulku();
    }//GEN-LAST:event_pridatPodmienkuButtonActionPerformed

    private void zmazatPodmienkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazatPodmienkuButtonActionPerformed
        podmienkaDao.deleteCondition(podmienkaDao.getById((long) podmienkyTable.getValueAt(podmienkyTable.getSelectedRow(), 0)));
        inicializujTabulku();
    }//GEN-LAST:event_zmazatPodmienkuButtonActionPerformed

    private void aktivneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivneRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktivneRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aktivneRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton neaktivneRadioButton;
    private javax.swing.JTable podmienkyTable;
    private javax.swing.JButton pridatPodmienkuButton;
    private javax.swing.JRadioButton vsetky;
    private javax.swing.JButton zmazatPodmienkuButton;
    // End of variables declaration//GEN-END:variables
}
