/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.Bank;
import core.db.entity.Condition;
import core.db.entity.User;
import core.db.impl.ConditionDaoImpl;
import core.db.ints.ConditionDao;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rastislav
 */
public class podmienkaFrame extends javax.swing.JFrame {

    private ConditionDao conditionDao = new ConditionDaoImpl();
    private Condition condition;
    
    public void inicializujTabulku() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        List<Condition> conditions = conditionDao.getAll();
        jTable1.removeAll();
        tableModel.setNumRows(conditions.size());
        for (int i = 0; i < conditions.size(); i++) {
            Long id = conditions.get(i).getId();
            String popis = conditions.get(i).getDescription();
            String vyraz = conditions.get(i).getExpression();
            Object[] data = {id, popis, vyraz};
            tableModel.setValueAt(id, i, 0);
            tableModel.setValueAt(popis, i, 1);
            tableModel.setValueAt(vyraz, i, 2);
        }
    }

    /**
     * Creates new form podmienkaFrame
     * @param user prihlaseny uzivatel
     */
    public podmienkaFrame(User user) {
        initComponents();
        inicializujTabulku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        popisTextArea = new javax.swing.JTextArea();
        popisLabel = new javax.swing.JLabel();
        pridatButton = new javax.swing.JButton();
        zatvoritButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        expressionTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        odstranitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        popisTextArea.setColumns(20);
        popisTextArea.setRows(5);
        jScrollPane1.setViewportView(popisTextArea);

        popisLabel.setText("Description");

        pridatButton.setText("Pridat");
        pridatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatButtonActionPerformed(evt);
            }
        });

        zatvoritButton1.setText("Zatvorit");
        zatvoritButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zatvoritButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Description", "Expression"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("Expression");

        odstranitButton1.setText("Odstranit");
        odstranitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pridatButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(odstranitButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(popisLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expressionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(zatvoritButton1)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zatvoritButton1)
                    .addComponent(pridatButton)
                    .addComponent(odstranitButton1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popisLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(expressionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void pridatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatButtonActionPerformed
        List<Boolean> vyplnenost = new ArrayList<>();
        Boolean mozesUlozit = true;
        condition = new Condition();
        if (popisTextArea.getText() != null) {
            condition.setDescription(popisTextArea.getText());
            vyplnenost.add(true);
        } else {
            popisTextArea.setText("Vyplne prosim popis");
            vyplnenost.add(false);
        }
        if (expressionTextField1.getText() != null) {
            condition.setExpression(expressionTextField1.getText());
            vyplnenost.add(true);
        } else {
            expressionTextField1.setText("Vyplnte prosim vyraz (cele cislo)");
            vyplnenost.add(false);
        }
        for (Boolean boolean1 : vyplnenost) {
            if (!boolean1) {
                mozesUlozit = false;
            }
        }
        if (mozesUlozit) {
            conditionDao.addCondition(condition);
            inicializujTabulku();
        }
    }//GEN-LAST:event_pridatButtonActionPerformed

    private void zatvoritButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zatvoritButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_zatvoritButton1ActionPerformed

    private void odstranitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranitButton1ActionPerformed
         conditionDao.deleteCondition(conditionDao.getById((long) jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        inicializujTabulku();
    }//GEN-LAST:event_odstranitButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField expressionTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton odstranitButton1;
    private javax.swing.JLabel popisLabel;
    private javax.swing.JTextArea popisTextArea;
    private javax.swing.JButton pridatButton;
    private javax.swing.JButton zatvoritButton1;
    // End of variables declaration//GEN-END:variables
}
